In [2]:
import importlib
import numpy as np

import callFortran
importlib.reload(callFortran) #ipython_only

<module 'callFortran' from '/Users/pmzrsg/source/pythonCallsFortran/wArray/callFortran.py'>

In [30]:
rows=2
columns=30
u = np.linspace(0, 1.0, num=rows*columns)
x = np.reshape(u, (rows, columns))
actual= callFortran.callFunction( x)
expected = np.exp(x)
np.testing.assert_almost_equal(actual,expected)

In [29]:

x

array([[0.        , 0.01694915, 0.03389831, 0.05084746, 0.06779661,
        0.08474576, 0.10169492, 0.11864407, 0.13559322, 0.15254237,
        0.16949153, 0.18644068, 0.20338983, 0.22033898, 0.23728814,
        0.25423729, 0.27118644, 0.28813559, 0.30508475, 0.3220339 ,
        0.33898305, 0.3559322 , 0.37288136, 0.38983051, 0.40677966,
        0.42372881, 0.44067797, 0.45762712, 0.47457627, 0.49152542],
       [0.50847458, 0.52542373, 0.54237288, 0.55932203, 0.57627119,
        0.59322034, 0.61016949, 0.62711864, 0.6440678 , 0.66101695,
        0.6779661 , 0.69491525, 0.71186441, 0.72881356, 0.74576271,
        0.76271186, 0.77966102, 0.79661017, 0.81355932, 0.83050847,
        0.84745763, 0.86440678, 0.88135593, 0.89830508, 0.91525424,
        0.93220339, 0.94915254, 0.96610169, 0.98305085, 1.        ]])

In [22]:
np.exp(x)

array([[1.        , 1.22140276, 1.4918247 ],
       [1.8221188 , 2.22554093, 2.71828183]])

In [24]:
x

array([[0. , 0.2, 0.4],
       [0.6, 0.8, 1. ]])